# Generated by Django 3.0.7 on 2020-11-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labtoratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=50)),
                ('lab_equipment', models.IntegerField(max_length=50)),
                ('lab_max_capacity', models.IntegerField(max_length=50)),
                ('lab_humidity', models.IntegerField(max_length=50)),
                ('lab_temperature', models.IntegerField(max_length=50)),
                ('lab_gas', models.FloatField(max_length=50)),
                ('lab_repair', models.IntegerField(max_length=50)),
            ],
        ),
    ]
