# Generated by Django 3.0.7 on 2020-11-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('member_xueyuan', models.CharField(max_length=50)),
                ('member_banji', models.CharField(max_length=50)),
                ('member_xuehao', models.CharField(max_length=50)),
                ('member_phone', models.CharField(max_length=50)),
                ('member_image', models.ImageField(blank=True, null=True, upload_to='member_img/')),
            ],
        ),
    ]
